Validate txn before entering mempool
Zilliqa/zq2 pull request #1128
Opened 2024-07-03 07:58 UTC by bzawisto

This pull request introduces several validation steps for received transactions before they are added to the mempool. While revm performs more detailed validation regarding the required gas limit and account checks, these preliminary steps help prevent transactions from getting stuck in the mempool. Specifically, nonce, gas limit, and transaction cost are now verified earlier.

For Scilla, there was previously no limit on transaction input size, which was indirectly controlled by the network buffer defaulting to 5MB. Additionally, ZQ1 specifies that the minimum gas required for any Scilla transaction, particularly for contract invocation, is 10.

Update: It has turned out that for Scilla there's limit for code size + extra checks have been added for gas limit (based on ZQ1 logic).

Addressed issue: https://github.com/Zilliqa/zq2/issues/1003

2024-07-03 08:29 UTC, rrw-zilliqa submitted a review, later dismissed
Looks good to me :-)

2024-07-03 08:29 UTC, rrw-zilliqa commented on zilliqa/src/transaction.rs
> +            return Ok(false);
Can we return a reason code here? It would be massively useful for application developers to know what has caused their txn to fail to be accepted.

2024-07-03 10:06 UTC, JamesHinshelwood requested changes
Thanks, looks good. Only thing I care about is that we remove the amount truncation.

2024-07-03 10:06 UTC, JamesHinshelwood commented on zilliqa/src/transaction.rs
> +            _ => return Ok(true),
Did you check if ZQ1 puts any limits on Scilla transaction sizes?

2024-07-03 10:06 UTC, JamesHinshelwood commented on zilliqa/src/transaction.rs
> +        if txn_cost > ZilAmount(account.balance) {
Use `u128` here too.

2024-07-03 10:06 UTC, JamesHinshelwood commented on zilliqa/src/transaction.rs
> +impl Mul for ZilAmount {
Where is this used?

2024-07-03 15:12 UTC, rrw-zilliqa commented on zilliqa/src/constants.rs
Ah, but I am, so that we can find all the constants we're using. Is there a way in which tooling can help us magically escape from this dilemma? We could mark our constants with macros and then extract a list programmatically?

2024-07-03 15:12 UTC, rrw-zilliqa commented on zilliqa/src/consensus.rs
> +            return Ok(false);
Want me to file an issue?

2024-07-08 17:38 UTC, JamesHinshelwood approved these changes

2024-07-08 17:38 UTC, JamesHinshelwood commented on zilliqa/src/consensus.rs
> +            return Ok(false);
@bzawisto Could you do the honours when merging this PR?

2024-07-08 17:38 UTC, JamesHinshelwood commented on zilliqa/src/constants.rs
Fair enough, I'll withhold my thoughts for now and we can keep them here.

2024-07-08 17:38 UTC, JamesHinshelwood commented on zilliqa/src/constants.rs
> +pub const EVM_MIN_GAS_UNITS: EvmGas = EvmGas(21000);
Thanks

2024-07-09 08:33 UTC, merged