add view to vote and QC
Zilliqa/zq2 pull request #516
Opened 2023-10-27 11:49 UTC by n-hutton

2023-11-03 13:29 UTC, theo-zil requested changes
LGTM if the log is changed

2023-11-03 13:29 UTC, theo-zil commented on zilliqa/src/message.rs
> +        warn!("Verify vote: {:?}", self);
This seems more like a trace, or info at most

2023-11-09 12:14 UTC, n-hutton commented on zilliqa/src/message.rs
> +        warn!("Verify vote: {:?}", self);
```suggestion
        trace!("Verify vote: {:?}", self);
```

2023-11-21 18:33 UTC, theo-zil approved these changes

2023-11-22 14:31 UTC, merged